name: universal_ffi
description: A drop-in replacement for dart:ffi for all platforms including web (using wasm_ffi).
version: 1.1.3
repository: https://github.com/vm75/universal_ffi
publish_to: none

environment:
  sdk: ^3.5.1

dependencies:
  ffi: ^2.1.3
  path: ^1.9.0
  wasm_ffi:
    git:
      url: https://github.com/dh0er/wasm_ffi.git

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

topics:
 - ffi
 - wasm
 - native
 - web
 - cross-platform

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
